# Generated by Django 2.2.4 on 2019-08-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_navbarmenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论'},
        ),
        migrations.AlterModelOptions(
            name='navbarmenu',
            options={'verbose_name': '导航栏菜单选项'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '文章'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户'},
        ),
        migrations.AlterField(
            model_name='navbarmenu',
            name='name',
            field=models.CharField(max_length=128, verbose_name='选项名称'),
        ),
        migrations.AlterField(
            model_name='navbarmenu',
            name='url',
            field=models.URLField(verbose_name='url'),
        ),
    ]
