# Generated by Django 2.2.4 on 2019-08-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190821_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb_url',
            field=models.URLField(blank=True, verbose_name='头图url'),
        ),
    ]
