# Generated by Django 2.2.4 on 2019-08-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='digest',
            field=models.CharField(blank=True, max_length=300, verbose_name='摘要'),
        ),
    ]
